name: moran
channels:
- defaults
dependencies:
- jupyter=1.0.0
- matplotlib=2.1.0
- numpy=1.12.1
- pandas=0.19.2
- python=3.6
- scipy=0.19.0
- sympy=1.0
- statsmodels=0.9.0
- pip:
  - axelrod==2.9.0
  - tqdm==3.4.0
